---
- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_sflogs }}"
    - emit-ara-html

- hosts: "{{ site_sflogs.fqdn }}"
  gather_facts: false
  tasks:
    # Use a block because play vars doesn't take precedence on roles vars
    - block:
        - import_role: name=upload-logs
        - import_role: name=emit-job-report
        - import_role: name=buildset-artifacts-location
      vars:
        zuul_log_url: "https://sftests.com/logs"
        zuul_logserver_root: /var/www/logs

